[project]
name = "auto-journal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "phonenumbers>=9.0.2",
    "requests>=2.32.3",
]
